// Code generated by "stringer -type=AbortReason"; DO NOT EDIT.

package cec

import "fmt"

const _AbortReason_name = "AbortUnrecognizedOpCodeAbortNotInCorrectModeAbortCannotProvideSourceAbortInvalidOperandAbortRefused"

var _AbortReason_index = [...]uint8{0, 23, 44, 68, 87, 99}

func (i AbortReason) String() string {
	if i >= AbortReason(len(_AbortReason_index)-1) {
		return fmt.Sprintf("AbortReason(%d)", i)
	}
	return _AbortReason_name[_AbortReason_index[i]:_AbortReason_index[i+1]]
}
