// Code generated by "stringer -type=DeviceType"; DO NOT EDIT.

package cec

import "strconv"

const (
	_DeviceType_name_0 = "DeviceTypeTVDeviceTypeRecDeviceTypeReservedDeviceTypeTunerDeviceTypePlaybackDeviceTypeAudioDeviceTypeSwitchDeviceTypeVidProc"
	_DeviceType_name_1 = "DeviceTypeInvalid"
)

var (
	_DeviceType_index_0 = [...]uint8{0, 12, 25, 43, 58, 76, 91, 107, 124}
)

func (i DeviceType) String() string {
	switch {
	case 0 <= i && i <= 7:
		return _DeviceType_name_0[_DeviceType_index_0[i]:_DeviceType_index_0[i+1]]
	case i == 15:
		return _DeviceType_name_1
	default:
		return "DeviceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
