// Code generated by "stringer -type=PowerStatus"; DO NOT EDIT.

package cec

import "strconv"

const _PowerStatus_name = "PowerStatusOnPowerStatusStandbyPowerStatusOnTransitionPowerStatusStandbyTransition"

var _PowerStatus_index = [...]uint8{0, 13, 31, 54, 82}

func (i PowerStatus) String() string {
	if i >= PowerStatus(len(_PowerStatus_index)-1) {
		return "PowerStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PowerStatus_name[_PowerStatus_index[i]:_PowerStatus_index[i+1]]
}
