// Code generated by "stringer -type=UserControl"; DO NOT EDIT.

package cec

import "strconv"

const (
	_UserControl_name_0 = "UcSelectUcUpUcDownUcLeftUcRightUcRightUpUcRightDownUcLeftUpUcLeftDownUcRootMenuUcSetupMenuUcContentsMenuUcFavoriteMenuUcExit"
	_UserControl_name_1 = "UcNumber0UcNumber1UcNumber2UcNumber3UcNumber4UcNumber5UcNumber6UcNumber7UcNumber8UcNumber9UcDotUcEnterUcClear"
	_UserControl_name_2 = "UcChannelUpUcChannelDownUcPreviousChannelUcSoundSelectUcInputSelectUcDisplayInformationUcHelpUcPageUpUcPageDown"
	_UserControl_name_3 = "UcPowerUcVolumeUpUcVolumeDownUcMuteUcPlayUcStopUcPauseUcRecordUcRewindUcFastForwardUcEjectUcForwardUcBackward"
	_UserControl_name_4 = "UcAngleUcSubpictureUcVideoOnDemandUcEPGUcTimerProgrammingUcInitialConfig"
	_UserControl_name_5 = "UcPlayFunctionUcPausePlayFunctionUcRecordFunctionUcPauseRecordFunctionUcStopFunctionUcMuteFunctionUcRestoreVolumeFunctionUcTuneFunctionUcSelectDiskFunctionUcSelectAVInputFunctionUcSelectAudioInputFunction"
	_UserControl_name_6 = "UcF1BlueUcF2RedUcF3GreenUcF4YellowUcF5"
)

var (
	_UserControl_index_0 = [...]uint8{0, 8, 12, 18, 24, 31, 40, 51, 59, 69, 79, 90, 104, 118, 124}
	_UserControl_index_1 = [...]uint8{0, 9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 95, 102, 109}
	_UserControl_index_2 = [...]uint8{0, 11, 24, 41, 54, 67, 87, 93, 101, 111}
	_UserControl_index_3 = [...]uint8{0, 7, 17, 29, 35, 41, 47, 54, 62, 70, 83, 90, 99, 109}
	_UserControl_index_4 = [...]uint8{0, 7, 19, 34, 39, 57, 72}
	_UserControl_index_5 = [...]uint8{0, 14, 33, 49, 70, 84, 98, 121, 135, 155, 178, 204}
	_UserControl_index_6 = [...]uint8{0, 8, 15, 24, 34, 38}
)

func (i UserControl) String() string {
	switch {
	case 0 <= i && i <= 13:
		return _UserControl_name_0[_UserControl_index_0[i]:_UserControl_index_0[i+1]]
	case 32 <= i && i <= 44:
		i -= 32
		return _UserControl_name_1[_UserControl_index_1[i]:_UserControl_index_1[i+1]]
	case 48 <= i && i <= 56:
		i -= 48
		return _UserControl_name_2[_UserControl_index_2[i]:_UserControl_index_2[i+1]]
	case 64 <= i && i <= 76:
		i -= 64
		return _UserControl_name_3[_UserControl_index_3[i]:_UserControl_index_3[i+1]]
	case 80 <= i && i <= 85:
		i -= 80
		return _UserControl_name_4[_UserControl_index_4[i]:_UserControl_index_4[i+1]]
	case 96 <= i && i <= 106:
		i -= 96
		return _UserControl_name_5[_UserControl_index_5[i]:_UserControl_index_5[i+1]]
	case 113 <= i && i <= 117:
		i -= 113
		return _UserControl_name_6[_UserControl_index_6[i]:_UserControl_index_6[i+1]]
	default:
		return "UserControl(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
