// Code generated by "stringer -type=notify"; DO NOT EDIT.

package raspberrypi

import "strconv"

const (
	_notify_name_0 = "notifyTxnotifyRx"
	_notify_name_1 = "notifyButtonPressed"
	_notify_name_2 = "notifyButtonRelease"
	_notify_name_3 = "notifyRemotePressed"
	_notify_name_4 = "notifyRemoteRelease"
	_notify_name_5 = "notifyLogicalAddr"
	_notify_name_6 = "notifyTopology"
	_notify_name_7 = "notifyLogicalAddrLost"
)

var (
	_notify_index_0 = [...]uint8{0, 8, 16}
)

func (i notify) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _notify_name_0[_notify_index_0[i]:_notify_index_0[i+1]]
	case i == 4:
		return _notify_name_1
	case i == 8:
		return _notify_name_2
	case i == 16:
		return _notify_name_3
	case i == 32:
		return _notify_name_4
	case i == 64:
		return _notify_name_5
	case i == 128:
		return _notify_name_6
	case i == 32768:
		return _notify_name_7
	default:
		return "notify(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
